<?php

return array(
//web渠道
    'web' => array(
	'public' => '官网',
	'baidu_search' => '百度搜索',
	'baidu_webunion' => '百度网盟',
	'360_search' => '360搜索',
	'360_webunion' => '360网盟',
	'sougou_search' => '搜狗搜索',
	'sougou_webunion' => '搜狗网盟',
	'xinshudsp' => '新数DSP',
	'qichuangdsp' => '企创DSP',
	'yunyingshang' => '运营商渠道',
        'lirenluntan'=>'丽人论坛',
        'wangtuiluntan'=>'网推论坛',
        'qqqun'=>'QQ群',
        'meiti'=>'媒体',
    ),
//wap渠道  
    'wap' => array(
	'public' => '官网',
	'baidu_search' => '百度搜索',
	'baidu_webunion' => '百度网盟',
	'360_search' => '360搜索',
	'360_webunion' => '360网盟',
	'sougou_search' => '搜狗搜索',
	'sougou_webunion' => '搜狗网盟',
	'xinshudsp' => '新数DSP',
	'qichuangdsp' => '企创DSP',
	'weixin3q' => '感恩节微信',
	'sms3q' => '感恩节短信',
	'weibo3q' => '感恩节微博',
	'weixinqun' => '微信群',
    ),
    //Android渠道
    'Android' => array(
	'public' => '官网',
	'fuyi' => '扶翼',
	'zhihuitui' => '智汇推',
	'fensitong' => '粉丝通',
	"baidu" => '百度手机助手',
	'360' => '360手机助手',
	'wandoujia' => '豌豆荚',
	'anzhi' => '安智市场',
	'oppo' => 'oppo市场',
	'ppzhushou' => 'pp助手',
	'xiaomi' => '小米应用商店',
	'huawei' => '华为应用商店',
	'yingyongbao' => '腾讯应用宝',
	'anzhuo' => '安卓市场',
	'meizu' => '魅族应用商店',
	'lianxiang' => '联想Store',
	'mumayi' => '木蚂蚁',
	'yingyonghui' => '应用汇',
	'Nduo' => 'N多市场',
	'91' => '91助手',
	'sogou' => '搜狗',
	'jifeng' => '机锋',
	'vivo' => 'vivo',
	'yiyonghui' => '易用汇',
	'renrenyao' => '人人摇',
	'qrcode' => "官网二维码",
	'limeiwxtvyaoyiyao'=>"力美微信电视摇一摇(微摇)",
        'wanpu' => '万普',
        'jinritoutiao'=>'今日头条',
    ),
//ios渠道
    'ios' => array(
	'app_store' => 'App_store',
	'dianru' => '点入',
	'limei' => '力美',
	'adwo' => '安沃',
        'wanpu' => '万普',
        'jinritoutiao'=>'今日头条',
    )
);
